version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - '22222:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
